### ISSUE TITLE
mesh.data.primitives:*-gpu-arrays returns uninitialized

### ISSUE THREAD

**Issue by azimut** [cbaggers/nineveh#10]
But c-arrays seems to work. I am using the versions on Quicklisp.
```
EXAMPLES> (nineveh.mesh.data.primitives:cube-gpu-arrays)
(#<GPU-ARRAY :UNINITIALIZED :backed-by :BUFFER>                                                      
 #<GPU-ARRAY :UNINITIALIZED :backed-by :BUFFER>) 
                                                    
EXAMPLES> (nineveh.mesh.data.primitives:cube-c-arrays)
(#<C-ARRAY :element-type G-PNT :dimensions (24)>                                                     
 #<C-ARRAY :element-type :USHORT :dimensions (36)>)  
```

**Comment by cbaggers** [comment]
Sounds like CEPL hadnt been initialized when these were called. Without a GL context there is no way for it to do things (like allocate memory) on the gpu.

Try running `(cepl:repl)` from your repl and then try again

**Comment by azimut** [comment]
That was it. Sorry, was trying to run block by block to understand this better. Thanks!

**Comment by cbaggers** [comment]
No problem, feel free to keep the questions coming :)
