### ISSUE TITLE
3D simplex noise is wrong

### ISSUE THREAD

**Issue by mfiano** [cbaggers/nineveh#13]
All 3D simplex noise variants are wrong and do not render anything but a sliver of garbage in the corner of the screen. I tried to reimplement them from scratch with varjo and it exhibits the same behavior. I copied Brian Sharpe's original code to shadertoy and that works fine, so I believe this might be an issue with the varjo compiler with regards to multiple-value-bind. That's just a guess though. Careful inspection is required. Here is the shadertoy demo https://www.shadertoy.com/view/4dGBzz

**Comment by mfiano** [comment]
Inspected this really hard all day and I found the problem.

In this file, line 10, 15, and 16 are wrong. You need to do subtraction before addition.

https://github.com/cbaggers/nineveh/blob/master/noise/simplex-helpers.lisp

Line 10 for example should be:

```lisp
;; correct
(x0 (+ (- p pi) (v3! (dot pi unskew-factor))))
;; not correct
(x0 (- p (+ pi (v3! (dot pi unskew-factor)))))
```

and likewise for the other 2 lines mentioned.

**Comment by cbaggers** [comment]
Cheers man https://github.com/cbaggers/nineveh/commit/9296984a0bdd2a086e59f6b5834972974b0bae4d
