### ISSUE TITLE
Varjo: Symbol 'NINEVEH.COLOR::PI-F' is unidentified.

### ISSUE THREAD

**Issue by jtmayer** [cbaggers/nineveh#5]
[nineveh-error.txt](https://github.com/cbaggers/nineveh/files/1043269/nineveh-error.txt)

**Comment by cbaggers** [comment]
Hi there @jtmayer, this symbols comes from [rtg-math](https://github.com/cbaggers/rtg-math) but the version in quicklisp does not have this yet.

You can either clone the latest `rtg-math` or wait for Nineveh to be in quicklisp. Everything I have in quicklisp is kept in sync.

If you chose to clone then I recommend using the `release-quicklisp` branch as this is the stable code that will be in the next release.

Thanks for checking this stuff out and reporting this issue :)

**Comment by jtmayer** [comment]
Okay, thanks for the pointer, I'll dereference it.
