### ISSUE TITLE
No package named "GLSL-SYMBOLS"

### ISSUE THREAD

**Issue by sparkecho** [cbaggers/nineveh#6]
Hi Baggers, when I load nineveh I encountered this error, and I can't figure it out where this package is. thx

**Comment by cbaggers** [comment]
Hi! you'll need to check out https://github.com/cbaggers/glsl-spec . Luckily very soon `glsl-spec` & `nineveh` with both be in quicklisp so this will get much easier.

**Comment by sparkecho** [comment]
Thanks Baggers. I know what's wrong now. The problem is the package **glsl-spec** I got is from quicklisp repository so it's **old** version, in that version **glsl-spec** doesn't have the directory **symbols**.

**Comment by cbaggers** [comment]
good to hear :) the next quicklisp release cycle will be soon so then all this will be easier. 
Thanks for raising the issue, always motivating to see people using this stuff :)
