### ISSUE TITLE
Lattice may be generating the wrong number of quads

### ISSUE THREAD

**Issue by djeis97** [cbaggers/nineveh#9]
Found on stream, lattice may be generating an extra or missing quad or row.

**Comment by cbaggers** [comment]
Ah, got it. We were using the latice-data function which is an older implementation, in the other streams we were using the nineveh functions with use the cffi variants from the same library

**Comment by cbaggers** [comment]
I've now made the *-data functions use the *-foreign functions which fixes both the lattice & sphere glitches we saw on the stream
